EXTRA_CFLAGS += -DISP_WDR_V3
EXTRA_CFLAGS += -DISP_MIV1
EXTRA_CFLAGS += -DISP_COMPAND
EXTRA_CFLAGS += -DISP8000NANO_BASE
EXTRA_CFLAGS += -DISP_MP_34BIT
EXTRA_CFLAGS += -DISP_FILTER
EXTRA_CFLAGS += -DISP8000NANO_V1802
